### ISSUE TITLE
Allow component-less image recipes.

### ISSUE THREAD

**Issue by commiterate** [aws/ec2-image-builder-roadmap#111]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**

Image Builder image recipes currently require a minimum of 1 component ([API](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-imagebuilder-imagerecipe.html#cfn-imagebuilder-imagerecipe-components), [Cfn](https://docs.aws.amazon.com/imagebuilder/latest/APIReference/API_CreateImageRecipe.html#imagebuilder-CreateImageRecipe-request-components)).

Users may not want any for pure workflow image recipes.

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**

Reduce the number of resources needed for an image recipe.

**Are you currently working around this issue?**

Creating a no-op component for recipes. For example:

```yaml
Resources:
  DummyLinuxComponent:
    Type: AWS::ImageBuilder::Component
    Properties:
      # ...
      Data: |
        schemaVersion: '1'
        phases:
          - name: build
            steps:
              - name: dummy
                action: Assert
                inputs:
                  stringIsEmpty: ''
      Platform: Linux
  DummyMacComponent:
    Type: AWS::ImageBuilder::Component
    Properties:
      # ...
      Data: |
        schemaVersion: '1'
        phases:
          - name: build
            steps:
              - name: dummy
                action: Assert
                inputs:
                  stringIsEmpty: ''
      Platform: macOS
  DummyWindowsComponent:
    Type: AWS::ImageBuilder::Component
    Properties:
      # ...
      Data: |
        schemaVersion: '1'
        phases:
          - name: build
            steps:
              - name: dummy
                action: Assert
                inputs:
                  stringIsEmpty: ''
      Platform: Windows
```

**Additional context**

None.
