### ISSUE TITLE
Using EventBridge events to trigger Image Pipeline builds

### ISSUE THREAD

**Issue by girishb-aws** [aws/ec2-image-builder-roadmap#54]
This will introduce the ability to use Event Bridge to trigger the creation of new images.

**Comment by budi-halim** [comment]
hi @girishb-aws Do you know if CFN Support is available for Image Builder Pipeline with Event Bridge? Console configuration seems to work but I could not find documentation regarding the CFN Parameters for EventBridge

**Comment by girishb-aws** [comment]
hey @budi-halim , we do not have any API changes in the implementation. So, there is no change in the CFN templates.

**Comment by chethansiddagiri** [comment]
Hey @girishb-aws - I do not see an option to add eventbridge rule to EC2 image builder through cli  or terraform aws provider.  Do you know if its available ?

**Comment by tarunb12** [comment]
EventBridge rules support directly targeting/triggering EC2 Image Builder image pipelines. See: [Use EventBridge rules to schedule a pipeline build
](https://docs.aws.amazon.com/imagebuilder/latest/userguide/ev-rules-for-pipeline.html#ev-rules-schedule-pipeline)

If you are aiming to directly trigger an image pipeline via CloudFormation, the `ImagePipelineExecutionSettings` property can be used on [AWS::ImageBuilder::Image](https://docs.aws.amazon.com/AWSCloudFormation/latest/TemplateReference/aws-resource-imagebuilder-image.html) to trigger when the pipeline is created/updated. Example:

```yaml
TriggeredImage:
  Type: AWS::ImageBuilder::Image
  Properties:
    # Natively triggers the pipeline when it is created or receives any update
    ImagePipelineExecutionSettings:
      DeploymentId: !GetAtt 'ImagePipeline.DeploymentId'
      OnUpdate: true
```
