### ISSUE TITLE
Add `permission` attribute to `WebDownload` and `S3Download` actions

### ISSUE THREAD

**Issue by robgero** [aws/ec2-image-builder-roadmap#72]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
What do you want us to build?

It would be nice to specify the permission for the downloaded file when using the `WebDownload` and `S3Download` actions.

It could look something like:

```yaml
name: DownloadMyKey
action: S3Download
inputs:
    - source: s3://mybucket/path/to/privatekey
      destination: /home/user/privatekey
      permissions: 400
```
and

```yaml
name: DownloadMyExecutable
action: WebDownload
inputs:
    - source: https://example.com/executable
      destination: /home/user/executable
      permissions: 550
```

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
What outcome are you trying to achieve, ultimately, and why is it hard/impossible to do right now? What is the impact of not having this problem solved? The more details you can provide, the better we'll be able to understand and solve the problem.

This is not hard/impossible to workaround. It would just be cleaner if I was able to specify the permission in the YAML.

**Are you currently working around this issue?**
How are you currently solving this problem?

Add commands to the user-data to fix the permissions on the files.

**Additional context**
Anything else we should know?

See how the `CreateFile` action works.
